### ISSUE TITLE
Take another look at the 'add another file'

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#107]
Currently the 'add another file' is in the location that most people expect submit to be. It's also too highly visible so attracts attention while it is a secondary action.

Dim the button a bit (or make it smaller) (or both).

**Comment by nekhvoya** [comment]
Please assign this ticket to me :)

**Comment by millefalcon** [comment]
@supakeen @nekhvoya Is this still being worked on ? If not, I would like to take this up.

**Comment by supakeen** [comment]
@millefalcon its being worked on should be in soon

**Comment by supakeen** [comment]
Done in #216.
