### ISSUE TITLE
Idea: resizable input window

### ISSUE THREAD

**Issue by kapsh** [supakeen/pinnwand#12]
Input window has relatively small height (fits around 30 lines maybe?). That makes editing larger texts before send inconvenient.

Usual user experience when working with such controls is to stretch them using mouse or just rely on automatic resize (github comment text area is a good example here).

**Comment by supakeen** [comment]
I've now made it so that the text input spans across the entire screen. To me that seems to work a bit better?

**Comment by kapsh** [comment]
LGTM too, thanks.
