### ISSUE TITLE
Stop using poetry as a build backend

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#121]
Due to some concerns listed in https://github.com/python-poetry/poetry/issues/3332 poetry does not as of yet support the PEP-621 form of shared metadata information.

As I want to be able to more easily switch build backends in the future let's switch to the pip build backend.

**Comment by CAM-Gerlach** [comment]
Just FYI—pip is a build _frontend_, not a backend. Setuptools, flit_core, Hatchling, pdm and poetry are all build backends (though some also offer build frontends too, at least for their own build system).

**Comment by supakeen** [comment]
Ah, thanks for the clarification :)

**Comment by supakeen** [comment]
Done and switched to `pdm`.
