### ISSUE TITLE
Ctrl+S shortcut to submit new paste

### ISSUE THREAD

**Issue by ChrisLovering** [supakeen/pinnwand#148]
Having a quick shortcut to submit is always quite nice. One solution for this would be to use the "standard" ctrl+s shortcut to submit.

This could be done by adding something like the below js to [pinnwand.js](https://github.com/supakeen/pinnwand/blob/e7cccd89414de584add537336d5898feac89f607/src/pinnwand/static/pinnwand.js)

```js
document.addEventListener('keydown', e => {
  if (e.ctrlKey && e.key === 's') {
      // Prevent the save dialog opening
      e.preventDefault();
      document.getElementById("pasteSubmit").click();
  }
});
```

This would require us to also add `pasteSubmit` as an id to the [submit button](https://github.com/supakeen/pinnwand/blob/e7cccd89414de584add537336d5898feac89f607/src/pinnwand/template/create.html#L40)

**Comment by supakeen** [comment]
I'm open to this, you don't specifically need to add the `id` to the submit button but you could use `document.querySelector()` to reference it. Would you like to open a PR for this?

**Comment by Kwpolska** [comment]
While implementing this, [make sure you don’t catch Ctrl+Alt+S as well](https://medium.engineering/the-curious-case-of-disappearing-polish-s-fa398313d4df).
