### ISSUE TITLE
CI to push Containerfile to container repo

### ISSUE THREAD

**Issue by ChrisLovering** [supakeen/pinnwand#152]
Having the image in quay.io updated automatically would be nice.

This could be done using an action such as https://github.com/redhat-actions/push-to-registry if remaining on quay.i is desired.

Alternately, Github's own ghcr.io package repo could be used, which might aid in discoverability due to it being listed in the left bar on the repo homepage.

In either case, I'd be happy to take this on myself, if approved.

As a further enhancement to this, additional build stages could be added that include common database engines, such as mysql & postgres, separately tagged.

For example, `supakeen/pinnwand:1.5.0` would be the base, with just sqlite support, `supakeen/pinnwand:1.5.0-postgres` could then have psycopg2 pre-installed.

**Comment by supakeen** [comment]
I'd be happy to have them published by CI to `ghcr.io` I like the idea of having the `-postgres` and/or `-mysql` postfixes on the containers. If you can tell me how or want to do it yourself please do :)
