### ISSUE TITLE
Expand browser tests

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#177]
With the recently added browser tests by @nekhvoya there is now room to expand them. They currently contain the single-paste scenario where a single paste is posted and verified to be posted.

Some things that could be covered are:

- multi-paste: use the add-file button to paste two (or more) files and verify they all show up in the page.
- file-upload paste: use the file-upload button to paste one file and verify it shows up in the page
- file-upload multi-paste: use the file-upload button to paste two (or more) files and verify they show up in the page
- file-drag paste: use the drag-n-drop to paste one file and verify it shows up in the page
- file-drag multi-paste: use the drag-n-drop to paste two (or more) files and verify they show up in the page

- paste deletion: paste a file and click the delete button, the page should be 404 when you renavigate to it

- verify that dark/light theme switching is working
- verify that the copy-button is working (clicking it should put the text of that file in your copy buffer)

- the general flow of adding files (and then removing them) (and then pasting them) is all javascript, it should be verified

There's probably plenty more but all of the above involve javascript; and while the actual routes and their inputs are being tested in the existing tests the browser tests could do these.

**Comment by nekhvoya** [comment]
Great! I'll start working on the scenarios this week

**Comment by supakeen** [comment]
A first batch of these was merged in #178 178.

**Comment by supakeen** [comment]
The second batch of these was merged in #183. Thank you! :)

**Comment by supakeen** [comment]
The third batch of these was merged in #184. Awesome.

**Comment by supakeen** [comment]
@nekhvoya How far along is that initial list now you think?

**Comment by nekhvoya** [comment]
@supakeen Out of the list above about 80% is done

**Comment by nekhvoya** [comment]
All the scenarios from the list are ready, except from the last point:
the general flow of adding files (and then removing them) (and then pasting them) is all javascript, it should be verified
I'm not sure I understand correctly which flow need to be covered. We already have scenarios for creation of pastes, adding files and deletion of pastes. Do we need to add a certain edge case scenario to this list?

Also, below is the list of additional tests that could be added:
* the Remove file functionality
* Repaste (for plain text and files)
* Download (separate files and archive)
* Toggle word wrap 
* Raw and Hex buttons
* Use longer URI
* Setting file name
* Possibly, text formats other then txt (needs to be discussed)

@supakeen let me know pls if any of those additional scenarios need(don't need) to be covered

**Comment by supakeen** [comment]
> All the scenarios from the list are ready, except from the last point: the general flow of adding files (and then removing them) (and then pasting them) is all javascript, it should be verified I'm not sure I understand correctly which flow need to be covered. We already have scenarios for creation of pastes, adding files and deletion of pastes. Do we need to add a certain edge case scenario to this list?

This is purely about the javascript side of things. Not the deletion *after* the paste has been pasted. If we already have tests covering that then it can be ignored :)


> 
> Also, below is the list of additional tests that could be added:
> 
>     * the Remove file functionality
> 
>     * Repaste (for plain text and files)
> 
>     * Download (separate files and archive)
> 
>     * Toggle word wrap
> 
>     * Raw and Hex buttons
> 
>     * Use longer URI
> 
>     * Setting file name
> 
>     * Possibly, text formats other then txt (needs to be discussed)
> 
> 
> @supakeen let me know pls if any of those additional scenarios need(don't need) to be covered

I'm happy to accept PRs for any of those tests. The routes are tested in the integration tests; but the buttons actually going to the right places isn't being tested so +1 to adding those.

**Comment by nekhvoya** [comment]
all the scenarios listed in this ticket were implemented and merged

**Comment by supakeen** [comment]
Awesome!
