### ISSUE TITLE
Are pastes being reaped properly?

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#182]
I've seen some evidence in `bpa.st`'s database and there is some circumstantial evidence from the Discord Python instance that pastes aren't properly getting reaped by the `PeriodicCallback` that should take care of this.

Note: pastes that have expired are still not visible because the `Show` page will delete the paste if it's visited while expired.

However, this leads to a needlessly large database. So let's investigate:

- [ ] Does the PeriodicCallback work?
- [ ] Are pastes being reaped on *all* show pages?
- [ ] Add test cases for these things.

**Comment by shtlrs** [comment]
I'd like to tackle this

**Comment by supakeen** [comment]
@shtlrs good questions.

1. Pastes should be reaped on the show pages (any of the APIs, the 'web'-part of the application) when they are encountered with an expiry date in the past, see for example: https://github.com/supakeen/pinnwand/blob/master/src/pinnwand/handler/website.py#L306
2. It runs, but does it keep running. I've encountered instances where a lot of expired pastes got left behind which can only mean that the PeriodicCallback has gotten stuck (sorry: I don't have more details on this).
3. Fixtures that create a new database with a given set of data in it is probably best; that way you'd also not need to monkey patch the ORM.

**Comment by shtlrs** [comment]
> It runs, but does it keep running. I've encountered instances where a lot of expired pastes got left behind which can only mean that the PeriodicCallback has gotten stuck (sorry: I don't have more details on this).

According to my very limited testing, it does. The task has kept on being invoked in the correct specified interval.

**Comment by supakeen** [comment]
Right, perhaps we can inject a fault in there and see if that breaks things if not then we can scrap that scenario off the list and only ensure that reaps also happen on access in every code path.

**Comment by shtlrs** [comment]
I've already made a test that makes sure it runs correctly, I'll finish the other tests and push it
