### ISSUE TITLE
The first paste input field doesn't have the Remove This File button is there are a multiple paste inputs

### ISSUE THREAD

**Issue by nekhvoya** [supakeen/pinnwand#191]
**Steps to reproduce:**
1. Open the Pinnwand
2. Click the Add Another File button a few times
3. Try to delete the first paste input

**Actual result:** the first paste input can't be deleted as the Remove This File button is absent 
![20](https://github.com/supakeen/pinnwand/assets/49349130/eb581631-064c-4c08-9aa6-b44e05fc9ce7)

**Expected result:** the Remove This File button should be displayed for all the inputs if there are multiple paste inputs displayed on the page (to be able to delete the first paste and only paste the 2d and 3d ones if needed)

**Comment by supakeen** [comment]
This might also be the time to think about adding confirmation if a file is removed that already has content in its textarea.

**Comment by supakeen** [comment]
Done in #208.
