### ISSUE TITLE
Is there a way to retrieve via API paste code from link?

### ISSUE THREAD

**Issue by DownDev** [supakeen/pinnwand#193]
Lets say i have a link to the paste. Is there a way to get the text stored under that text using API?

**Comment by supakeen** [comment]
There is no such route in the current API (`/api/v1`), though that needs to added. It seems weird that it's missing.

The deprecated API has one at (`/json/show/:paste-id`), for example: https://bpa.st/json/show/YDQA but it only shows the first file.

**Comment by supakeen** [comment]
PR was merged, needs docs.
