### ISSUE TITLE
Text area for a paste should support tab key and, text should be monospaced.

### ISSUE THREAD

**Issue by Dude-X** [supakeen/pinnwand#20]
While entering text in the text box of bpaste, it should allow me to use tab to space things out without navigating to the next "element".

Also the text i enter should be in a monospaced font so that it's not difficult to line up text.

**Comment by supakeen** [comment]
Monospaced font on the textarea is an easy fix, tab not moving to the next input might be impossible without javascript but I'll take a look.

**Comment by supakeen** [comment]
I updated the stylesheet to put the textarea to monospace but I can't find a neat way to prevent tab from going to the next field without javascript (and pinnwand tries to stay javascript free).

**Comment by Dude-X** [comment]
No problem. I can respect the lack of javascript. Thanks!
