### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by shtlrs** [supakeen/pinnwand#213]
Currently, loggers are provided thanks to `logging.get_logger`, which uses a default format.

I think it'll especially be helpful to have `timestamps` in logs, so that users can trace logs back in time.

This can be easily done by centralizing log bootsrapping in its own module.

I can PR this as well if it's approved.

**Comment by supakeen** [comment]
Hey @shtlrs that sounds like a great idea. Are you planning to write your own log formatter or are you going to use a pre-canned one like the one provided by `rich`?

**Comment by shtlrs** [comment]
> Hey @shtlrs that sounds like a great idea. Are you planning to write your own log formatter or are you going to use a pre-canned one like the one provided by `rich`?

I was just thinking about something pretty basic and standard like I've seen in so many projects
```py
# logger.py
import logging


def get_logger(name: str):
    logger = logging.getLogger(name)

    if not logger.handlers:
        handler = logging.StreamHandler()
        logger.addHandler(handler)

    logger.setLevel(logging.DEBUG)
    for handler in logger.handlers:
        formatter = logging.Formatter("%(asctime)s | %(name)s | %(levelname)s | %(message)s")
        handler.setFormatter(formatter)

    return logger
```

Then again, depends on what you want for the handlers, but that can change.

**Comment by supakeen** [comment]
Let's move this into a PR, I have some remarks about it but the general idea is good. 

Let's make sure we don't register handlers or formatters unless we're being executed in `__main__` so people using `pinnwand` as a library can do their own configuration of the logger (do people even do that?).

**Comment by shtlrs** [comment]
> Let's move this into a PR, I have some remarks about it but the general idea is good.
> 
> Let's make sure we don't register handlers or formatters unless we're being executed in `__main__` so people using `pinnwand` as a library can do their own configuration of the logger (do people even do that?).


Usually, the thing that's configured is the log level. But you can configure handlers too, just like `Django` does it. But I don't quite see the need to see such thing here. 

You make a logger and register under the `pinnwand` name, and people can then retrieve it from the logger manager and do whatever they want on it.

I'll make a PR for this and we can discuss it as you please :D
