### ISSUE TITLE
Can't install following the web instructions

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [supakeen/pinnwand#218]
Following this part of the [docs](https://pinnwand.readthedocs.io/en/latest/installation.html), it states that to install pinnwand we should type: `python3 -m venv virtual-environment virtual-environment/bin/pip install pinnwand`.

But whenever I try that, I got: `Error: Unable to create directory '/home/pastebins/pinnwand-1.5.0/virtual-environment/bin/pip'` and therefore I can't use `virtual-environment/bin/pinnwand http` to start pinnwand.

I've also tried `pip3 install --user pinnwand` but then I can't find the executable anywhere.

I'm a bit lost here.

EDIT: I can't use docker.

Cheers

**Comment by wookie184** [comment]
I think that's an error with how the docs are being displayed,
`python3 -m venv virtual-environment virtual-environment/bin/pip install pinnwand` is displayed on one line but it's actually two commands.

```python
python3 -m venv virtual-environment
```
and 
```python
virtual-environment/bin/pip install pinnwand
```

**Comment by PeGaSuS-Coder** [comment]
Oh, that makes much more sense.
I've managed to install it from source and I must say that I'm quite impressed with this piece of software.
Great job!

**Comment by supakeen** [comment]
That's a nice bug, thanks for PR #223 @wookie184 which fixes this.
