### ISSUE TITLE
Load environment variables from `.env` file

### ISSUE THREAD

**Issue by shtlrs** [supakeen/pinnwand#227]
Currently, `pinnwand` checks for environemnt variables that it loads to run the api, etc.

However, during development, it should be useful if these environment variables could be loaded up from a `.env` file.

This will help avoid issues such as committing files where config has been modified unintentionally.

**Comment by supakeen** [comment]
Agreed, it'd be nice and we can probably use one of the pre-existing libraries to do this. It might require a slight rethink of how the environment things are currently hacked into the settings.

**Comment by shtlrs** [comment]
> Agreed, it'd be nice and we can probably use one of the pre-existing libraries to do this. It might require a slight rethink of how the environment things are currently hacked into the settings.

Indeed, the change actually involves two things
1. Inclusion of th e`python-dotenv` package
2. Only **one** LOC addition.

I have a branch where I added & documented & tested this, and it works.

**Comment by supakeen** [comment]
I'm fine with using (and depending on) `pydantic` it seems like a good fit here as long as we can set it up in such a way that it's compatible with the current configuration methods (for which I think we have tests).

**Comment by shtlrs** [comment]
It should be possible, I'll make the change for it.

**Comment by shtlrs** [comment]
@supakeen I think that eventually, i'll just go with the dotenv package.

The reason for that is that with pydantic, things get a bit complicated since we also rely on a configuration file.
The precedence order should be
1. Config file
2. Environment
3. Environment file

The problem is that when we make the config a pydantic model, we lose control on what gets executed first.
Instantiating the pydantic model will just look at the environment & env file, and override the defaults.

Overriding the constructor doesn't work, and things start getting complicated since we'll need to
1. call super's init 
2. call the method to load from config file
3. call super's init again, to load from env and override any variable from the config path

The reason we call super twice is because the model's attributes are descriptors, so upon setting their values, some instance fields need to exist first. Which means that in case we try to load from config file first, those instance attributes won't be there since super's init is what instantiates them --> AttributeError is thrown


Anyway, I'll just spare you the details, and keep it simple as the implications of using pydantic like this aren't worth it

**Comment by supakeen** [comment]
I always prefer simple. Is that the normal precedence order where the environment file would override the actual environment?

**Comment by shtlrs** [comment]
> I always prefer simple. Is that the normal precedence order where the environment file would override the actual environment?

I don't know if there's a standard for this, but looking at how docker does it, the actual environment takes precedence.

I thought about the file first since we're not including it in VCS. It's only going to be for development purposes.

So if someone wants to quickly test pinnwand with a certain value, it's easier to set it from withing the env file than doing it from shell.

It's up to us obviously, what do you think?

**Comment by supakeen** [comment]
I'd say the most important is the environment, then the `.env` file, then the configuration file. This lets me quickly run `pinnwand` with `FOO=bar pinnwand http` or such to test a new configuration option.

**Comment by shtlrs** [comment]
> I'd say the most important is the environment, then the `.env` file, then the configuration file. This lets me quickly run `pinnwand` with `FOO=bar pinnwand http` or such to test a new configuration option.

@supakeen Sounds good, I've opened #260
