### ISSUE TITLE
ModuleNotFoundError: No module named 'http.cookies'; 'http' is not a package

### ISSUE THREAD

**Issue by shtlrs** [supakeen/pinnwand#228]
This error seems to happen particulary in `Pycharm` when I try to make a new config to run the `pinnwand` package with speciefic attributes to target the different CLI commands.

It first drove me crazy, but the issue is coming from a name conflict with the built-in Python `http` library .

Debugging is alot easier with `Pycharm`, at least to me. 

Would you be up to renaming the `http` module to `app`, since what it does eventually is make the app instance that'll later be ran.

**Comment by supakeen** [comment]
I'm up for renaming it.

**Comment by shtlrs** [comment]
It does, at least to me as I'm not sure about how others do but I've found myself committing and dropping whenever debugging, which is a bit unpleasant.

I'll PR this now, it's quite the simple change.
