### ISSUE TITLE
Fix consume ratelimit config

### ISSUE THREAD

**Issue by wookie184** [supakeen/pinnwand#242]
Configuration for rate limits lets you set the consume rate:
https://github.com/supakeen/pinnwand/blob/e737aba402548f83bc458c62ac6e10e69419f2b1/src/pinnwand/configuration.py#L12-L26

However, this configuration is not used, instead the consume value is always 1:
https://github.com/supakeen/pinnwand/blob/e737aba402548f83bc458c62ac6e10e69419f2b1/src/pinnwand/defensive.py#L46

**Comment by shtlrs** [comment]
I've also noticed that the `Limiter.consume` method takes a `key` and `num_tokens` argument.
https://github.com/falconry/token-bucket/blob/4d94f6418e4f1d6dfc641e854aa5ec85b7e0c735/token_bucket/storage.py#L126

This means that we could simplify the `defensive.ratelimit_area` dictionary to simply map the areas to a `Limiter` instance, and use the request's `ip` address as the `key` which will identify the right consumption bucket. And the `num_tokens` param will be passed the configuration's consumption value

What do you guys think of implementing this along with the bug fix ?
