### ISSUE TITLE
PEBCAK

### ISSUE THREAD

**Issue by TehPeGaSuS** [supakeen/pinnwand#248]
This is a call for help :)

When I use `cat <file> | curl -X POST -F 'raw=<-' https://0bin.xyz/curl`, the URL returned is localhost.

What am I missing for it to return something like `Paste URL:   https://0bin.xyz/ABCDEFGHIJ`?

Thanks in advance

**Comment by TehPeGaSuS** [comment]
Sorry for the delay but IRL caught me unexpectedly.

I do self-host the instance and after adding `ProxyPreserveHost On` to the Apache vhost all is fixed!

Sorry for the noise! :grin:

**Comment by gvoysey** [comment]
because i just hit this in nginx, writing it down here: 

```
server{
       # corp stuff elided here
        location /{
                 proxy_pass http://localhost:8000;
                 proxy_buffering off;
                 proxy_set_header Host $host;
                 proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                 proxy_set_header X-Forwarded-For $http_x_forwarded_for;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-Host $host;
                 proxy_set_header X-Forwarded-Port $server_port;
        }
}```
