### ISSUE TITLE
On a small screen the buttons fall out of line

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#254]
The new buttons that got added in #250 fall out of line when the screen is small.

![Screenshot from 2024-03-09 13-24-17](https://github.com/supakeen/pinnwand/assets/39536295/24cbf248-9e4d-4076-b936-ca1c4e6a0624)

**Comment by hanish-sx** [comment]
@supakeen I'm thinking, we can add `flex` on the container and add `margin-left: auto` to the remove button. What do you think ? If that is Okay, I can work on this. 

It will look something like this,

![image](https://github.com/supakeen/pinnwand/assets/103116961/a8997f34-16fb-4a73-956a-52881bb06826)

**Comment by millefalcon** [comment]
@supakeen I'm thinking we can add `flex` to the container and add `margin-left: auto` to the remove now button.
If that is Okay, I can work on this.

It will look something like this,
![image](https://github.com/supakeen/pinnwand/assets/16983964/714fc7a8-6b07-4fd0-83ce-10f2d29de2a5)

**Comment by supakeen** [comment]
@millefalcon of course you can work on this; just to be sure: this happens in multiple places (also on the new paste page).

**Comment by millefalcon** [comment]
@supakeen Got it. I'm kinda not sure where exactly we should put the `margin-left: auto`. I see the "remove" button in the create paste is added using javascript, so should i add the class there, or just put it in the scss ?
