### ISSUE TITLE
Long pastes aren't shown completely until sent

### ISSUE THREAD

**Issue by TehPeGaSuS** [supakeen/pinnwand#279]
Apparently, [my instance](https://pastebin.ptirc.org/) doesn't like long pastes.

Whenever I paste something with like 200 lines, the `paste field` only shows the first ~100 lines.

This seems to happen only when building from source. If i use `pip3 install pinnwand` all works as expected.

I have no idea why and I'd like some help on this one.

Using Apache as reverse proxy.

Thanks in advance

**Comment by TehPeGaSuS** [comment]
This seems to have solved with b57b6f35e2e4ecd61ad37b4ba18baf106493826e and 6f890a7b98071dc1ab3a2e06e7cb71b21ce6ad66 apparently.

**Comment by supakeen** [comment]
Good, I need to cut a release.
