### ISSUE TITLE
Paste gets cutoff at the bottom of the textarea

### ISSUE THREAD

**Issue by millefalcon** [supakeen/pinnwand#282]
The paste gets cutoff a little bit at the bottom of the textarea.

![image](https://github.com/user-attachments/assets/a7abae3b-6d6a-4270-9eb0-828a10010314)

If we remove the `height: 100%` from the textarea, it seems to fix it.

![image](https://github.com/user-attachments/assets/60ac74b0-f58d-40d9-a246-038854fccb3f)

Please let me know, if this annoys anyone, I can raise a PR :+1:

**Comment by supakeen** [comment]
This annoys me now that I see it :)

**Comment by millefalcon** [comment]
@supakeen huh, it's weird. I can't see it on `master` :/
