### ISSUE TITLE
curl api

### ISSUE THREAD

**Issue by SoniEx2** [supakeen/pinnwand#31]
http://sprunge.us (if that thing is still up) has a CLI API, could you have one too?

**Comment by supakeen** [comment]
I'll leave this ticket open to track this but in the `multi-file` branch which I plan to finish up over this week there's now the following:

    € echo "foo" | curl -X POST http://localhost:8000/curl -F "expiry=1day" -F "lexer=python" -F 'raw=<-'
    Paste URL:   http://localhost:8000/OE
    Raw URL:     http://localhost:8000/raw/GU
    Removal URL: http://localhost:8000/remove/GQBHGJYKRWIS34D6FNU6CJ3B5M
    € curl http://localhost:8000/raw/GU
    foo%
    €

I find it a bit hard to preselect values for the others. The expiry I can imagine to default to 1day but the lexer is a bit harder. What would you expect?

**Comment by SoniEx2** [comment]
plain with an option to force a highlighter (e.g. `https://example.org/OE?python`) but I'm okay with that.

(or maybe combine the lexer and paste? `-F 'python=<-'`?)

**Comment by supakeen** [comment]
I'll have this for now:

    € echo "foo" | curl -X POST http://localhost:8000/curl -F 'raw=<-'
    Paste URL:   http://localhost:8000/PU
    Raw URL:     http://localhost:8000/raw/QM
    Removal URL: http://localhost:8000/remove/YI5EUQ62IZTB4OWALZRYX63HYM
    € echo "foo" | curl -X POST http://localhost:8000/curl -F 'raw=<-' -F 'lexer=nonexistent'
    Invalid `lexer` supplied.
    € echo "foo" | curl -X POST http://localhost:8000/curl
    Invalid `raw` supplied.
    €

It preselects ``1day`` and ``text`` for expiry and lexer respectively. Forcing a lexer is something to think about with the progress towards multi-file in 1 paste and I've been against it because the rendering is quite resource intensive, that'll be a separate ticket.

I'll keep this ticket open and update it when the branch is merged and deployed.

**Comment by altendky** [comment]
I have to admit that `| nc termbin.com 9999` is nice...  metadata could even just be set by repasting now that we have that (wasteful i know but...).  Or maybe `| nc python3.bpaste.net`. :]  Anyways, not sure how much I personally will use this and I haven't thought about it much so don't worry too much about my take, but figured I'd share it anyways.

**Comment by supakeen** [comment]
I'd still love to support ``nc`` in the same way however it'd paste with the ``text`` lexer selected.

It is possible to envision some sort of format here where you *can* give the lexer but it won't be as pretty to use as the termbin example (which seem to be doing weird stuff).

Say one could `rpartition` on a newline and if the last newline is a valid lexer then use that however that seems fiddly :)

**Comment by altendky** [comment]
It would probably be prohibitive for various reasons but note the lexer selection by domain thought.  I agree that inline lexer specification isn't a super idea.

**Comment by SoniEx2** [comment]
lexer selection by -F seems fairly easy but maybe I'm wrong...

**Comment by supakeen** [comment]
It's entirely possible framework-wise but I don't know if it's that much easier. The entire ``<-`` is already badly known (I think) among curl users.

Is it that much better than having an extra field for the lexer?

As for @altendky I've split out netcat support to a separate ticket: https://github.com/supakeen/pinnwand/issues/32 and renamed this one to 'curl api'.

**Comment by supakeen** [comment]
This has been deployed, see the README for usage.
