### ISSUE TITLE
As an impatient keyboard enthusiast, I want to quickly submit after writing my paste 

### ISSUE THREAD

**Issue by cdunklau** [supakeen/pinnwand#42]
The current setup on the create page makes me hit tab four times to get from the textarea to the paste button. I often just use the mouse instead, and that makes me (*entirely* irrationally) **angry**.

The controls are currently ordered:

1. textarea
2. lexer
3. filename
4. expiry
5. Paste!
6. add file

In "impatient mode", I only care about paste, and *occasionally* lexer, and even then I usually set lexer first with the mouse before typing. So that's three controls I as good as never need, making me abuse my poor tab key.

When I want to make a new paste, I already know what language it will be (thus lexer), and what kind of thing I'll be writing (thus filename, if I'll make more than one)... and all that before know exactly what I want to type. Just moving the lexer and filename controls above the text input (like Gist has it) would get two controls out of my way.

Expiry is another thing. I *never* use that, I use bpaste for one-off things that nobody cares about after several *minutes*, much less a day or a week. It should be after the paste button, probably even after the add file control.

So, if I had my way, the order would be:

1. lexer
2. filename
3. textarea
4. Paste!
5. add file
6. expiry

**Comment by supakeen** [comment]
For a start I've moved (your) new paste button before the lexer and redeployed, let me think about the tabindex and how that ties into 'multi file' and such :)

**Comment by supakeen** [comment]
I have moved the lexer/filename above the textarea now, this means upon entering the site you can paste and immediately tab to paste. Let's see if people dislike the change :)

**Comment by cdunklau** [comment]
Nah, it's perfect. 👍
