### ISSUE TITLE
"Python" should mean Python 3

### ISSUE THREAD

**Issue by tritium21** [supakeen/pinnwand#45]
(This was initially going to be titled "Python highlighter does not highlight async/await")

Python should default to Python 3, and Python 2 should be its own separate drop down choice.  I don't know if this is something you actually control, or if its auto-populated by the highlighter.  If it is something you control, defaulting the unqualified Python to Python 3 makes the most sense.

Or the third option of having no unqualified Python option, and renaming it to Python 2 might be more palatable.

**Comment by supakeen** [comment]
It's currently the exact list Pygments gives us, I could see if an issue there would gain any traction and if not probably make a custom mapping for pinnwand.

**Comment by supakeen** [comment]
Updating Pygments in the dependencies fixed this issue! See Pygments changelog here: https://pygments.org/docs/changelog/#version-2-5-0
