### ISSUE TITLE
Replacement for the deprecated JSON API?

### ISSUE THREAD

**Issue by sbraz** [supakeen/pinnwand#47]
Hi,
If the JSON API is deprecated, why does the replacement endpoint require a CSRF token and return HTML?

I'm slightly confused as to what the best way to write a script to send pastes is. I like the idea of a JSON API more than the curl endpoint because it's prettier to parse with Python.

**Comment by supakeen** [comment]
Hey @sbraz the non-deprecated API is still being written and I should bump it to the top of my priority list.

The old deprecated API is fine to keep using for now (either posting directly to / or to /json/new) as I do plan to keep them in deprecated state for quite a while. They however don't support multi-file pastes. Something which I was planning for the new API.

**Comment by sbraz** [comment]
Well I made a script that gets the CSRF token from the main page so I'll keep using that now. 
It's good to know that you have something else in mind for the future. Maybe the "deprecated" message should be removed from pastes to avoid scaring users until there is an alternative?

**Comment by supakeen** [comment]
I've been doing some work on this code-wise and documentation wise. You can take a look at: https://pinnwand.readthedocs.io/en/latest/usage.html

That page lists all current ways of programmatically sending code to ``pinnwand`` including the new ``v1`` API which is the one you're supposed to be using.
