### ISSUE TITLE
Provide filename in download endpoint's Content-Disposition header

### ISSUE THREAD

**Issue by sbraz** [supakeen/pinnwand#49]
I think it would be nice to pass the filename (if available) here instead of the ID:
https://github.com/supakeen/pinnwand/blob/eed52c9b9dd1afe584a4ad2fe35a82a6a4871ef8/pinnwand/http.py#L288

**Comment by supakeen** [comment]
I've been thinking about this but I also don't particularly like the idea of having user input go towards another user.

Perhaps a combination of the file.slug and the filename?

**Comment by sbraz** [comment]
Yes maybe you don't want to let users change the extension for security reasons, otherwise people will start using the site to share malicious scripts or something. I guess there's no good solution here…

**Comment by supakeen** [comment]
It really depends on the operating system being used, I'd be fine with doing something akin to ``filename={file.filename}-{file.slug}.txt`` unless someone sees a flaw with that.
