### ISSUE TITLE
Add a URL to /json/new

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#5]
Currently the json/new endpoint returns only a paste_id and a removal_id. It'd be neat if a URL field gets returned too. This would require the hostname to be configured somewhere.

**Comment by kapsh** [comment]
What URL should it return, for humans of for api? I'm thinking that latter is more reasonable for using in things like console clients for quick uploading. As part of #9 I', planning to add two fields into response from `/json/new`: paste_url and raw_url.

> This would require the hostname to be configured somewhere.

Can `RequestHandler.request.host` be used to determine where application is hosted?

**Comment by supakeen** [comment]
Using requesthandler.request.host is fine for now (or the fullpath as you have right now in your pull request).
