### ISSUE TITLE
Blank lines don't survive copy paste

### ISSUE THREAD

**Issue by altendky** [supakeen/pinnwand#67]
![image](https://user-images.githubusercontent.com/543719/77554422-6825b580-6e8c-11ea-8d97-16cfac85975a.png)

The remaining ones seem to have whitespace in them.

**Comment by supakeen** [comment]
Interesting, that's definitely a bug, I'll take a look and probably PR it to pygments-better-html.

**Comment by supakeen** [comment]
Closed, redeployed bpaste to fix the issue as well. Will only be fixed for newly created pastes.
