### ISSUE TITLE
Change configuration format

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#7]
The current configuration is a settings.py file that is part of the project. This is less than ideal.

With the current command line interface it should be possible to pass a configuration file from the command line (with -c/--config) which will then get used.

I'd prefer using toml for this, the configuration file would then replace the settings file.

**Comment by kapsh** [comment]
How do you install and run this application on bpaste? I've chosen docker for my local instance and just reading settings from environment variables now (kapsh@73f0b1b14b194ecf54bc71a2f620b9171c40da66).

**Comment by supakeen** [comment]
I do run them containerized however I feel like having these configuration items be passed as flags to click (which can also be set through environment variables I think?) would be better.

Otherwise we could switch to tornado.option which allows configuration to be passed in that way.

**Comment by kapsh** [comment]
True, it's even more simple to do with click, no need to read os.environ for each variable. 
https://click.palletsprojects.com/en/7.x/arguments/#environment-variables

**Comment by supakeen** [comment]
Done with a ``--configuration-path`` option which overwrites the general configuration if present.
