### ISSUE TITLE
Incorrect coloring in dark mode

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#76]
![image](https://user-images.githubusercontent.com/39536295/82831053-a143cb80-9eb7-11ea-9997-591b39d5156b.png)

The 'print' part should get a different color.

**Comment by altendky** [comment]
Apparently screenshots were in order.  I get _no_ apparent coloring in ether light or dark.  As far as I can tell I'm submitting it with Python selected.

https://bpa.st/E5HA

![image](https://user-images.githubusercontent.com/543719/82832017-f7991600-9e87-11ea-9d76-93d168af4e6a.png)

![image](https://user-images.githubusercontent.com/543719/82832027-01bb1480-9e88-11ea-881f-2afa9f46e89a.png)

**Comment by supakeen** [comment]
I see something weird here as well; you need to do a hard refresh (ctrl+f5 or cmd+r depending on OS), that issue is being tracked in https://github.com/supakeen/pinnwand/issues/74 as it keeps rearing its head.

After that you should see at least some coloring though I agree that the 'name' part of a function should have a different color in dark mode.

**Comment by altendky** [comment]
Ah, ok.  Yeah, just following my link loaded it with coloring.  I forgot about that one.  Now I do also see your point about dark mode specifically.

**Comment by supakeen** [comment]
Mrm on this demo: https://pygments.org/demo/#try i can't really find many dark themes which color function names differently. Now I'm doubting myself if the theme had any. Will search for old screenshots :)

**Comment by supakeen** [comment]
I'm going to consider this to not be a bug and instead see this as something up for improvement in https://github.com/supakeen/pinnwand/issues/78
