### ISSUE TITLE
Make tab optionally insert 4 spaces

### ISSUE THREAD

**Issue by tritium21** [supakeen/pinnwand#90]
It is highly annoying to scratch type example code in the textarea.  It would be nice if tab inserted a usable number of spaces.

**Comment by bensimner** [comment]
But only for Python!

Other languages (e.g. Makefile) should insert tabs.
Or it should be a per-language UI option (e.g. checkbox).

**Comment by supakeen** [comment]
This will be in the 1.3.0 release.
