### ISSUE TITLE
Download all files in a paste

### ISSUE THREAD

**Issue by mweinelt** [supakeen/pinnwand#92]
When many files are pasted and you want to download them all clicking each link and scrolling gets cumbersome.

A button to download all files in a paste would be appreciated.

The server would probably have to put all files in an archive before offering the download.

**Comment by supakeen** [comment]
Mrm, what kind of archive would you suggest (this is, same as single-file download) a tricky thing to get right.

**Comment by mweinelt** [comment]
Probably `zip` for everyone and maybe `tar.zstd` or something fancy for the *nix people.

**Comment by supakeen** [comment]
Implemented, will be in the 1.3.0 release.
