### ISSUE TITLE
Default Lexer is not selected for additional files

### ISSUE THREAD

**Issue by mweinelt** [supakeen/pinnwand#97]
When I click "Add file" it uses a different lexer than what was selected for the original file.

**Comment by supakeen** [comment]
Would you say it needs to track the initially selected language or the last file's language?

**Comment by mweinelt** [comment]
The additional files preselect ABAP. Anything but ABAP would be fine :laughing:

**Comment by supakeen** [comment]
Haha, I presume this is without `preferred_lexers` set?

**Comment by mweinelt** [comment]
Correct.

**Comment by supakeen** [comment]
Fix written, will be in 1.2.2.
